[package]
name = "q3-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.17", features = ["derive"] }
serde = "1.0.195"
serde_derive = "1.0.195"
serde_json = "1.0.111"
